version: "3.9"
services:

  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=transactions
    container_name: transactions-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - transaction_network
  
  cache:
    container_name: transactions-cache
    image: redis:7.0
    ports:
      - 6379:6379
    networks:
      - transaction_network
    
  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - transaction_network

  kafka-queue:
    image: wurstmeister/kafka:latest
    depends_on: [zookeeper]
    container_name: transactions-kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka-queue:29092,LISTENER_DOCKER_EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://kafka-queue:29092,LISTENER_DOCKER_EXTERNAL://127.0.0.1:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_EXTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CREATE_TOPICS=transactions-validate:1:1,transactions-update-status:1:1
    ports:
      - 9092:9092
    networks:
      - transaction_network
  
  transactions-service:
    build: 
      context: ./src/transactions-api
      dockerfile: ../../.docker/transactions-api.dockerfile
    container_name: transaction-api
    ports:
      - 8080:3000
    depends_on: [kafka-queue, postgres, cache]
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=transactions
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_TYPE=postgres
      - KAFKA_BROKERS=kafka-queue:29092
      - TRANSACTION_VALIDATE_TOPIC=transactions-validate
      - TRANSACTION_UPDATE_STATUS_TOPIC=transactions-update-status
      - TRANSACTION_VALIDATE_CONSUMER_GROUP=transactions-validate-group
      - TRANSACTION_UPDATE_STATUS_CONSUMER_GROUP=transactions-update-status-group
      - REDIS_URL=transactions-cache:6379
      - REDIS_TTL=5000
    networks:
      - transaction_network
    
  anti-fraud-service:
    build: 
      context: ./src/anti-fraud-service
      dockerfile: ../../.docker/anti-fraud-service.dockerfile
    container_name: anti-fraud-service
    depends_on: [kafka-queue]
    environment:
      - KAFKA_BROKERS=kafka-queue:29092
      - TRANSACTION_VALIDATE_TOPIC=transactions-validate
      - TRANSACTION_UPDATE_STATUS_TOPIC=transactions-update-status
      - TRANSACTION_VALIDATE_CONSUMER_GROUP=transactions-validate-group
      - TRANSACTION_UPDATE_STATUS_CONSUMER_GROUP=transactions-update-status-group
    networks:
      - transaction_network

volumes:
  postgres_data:
    driver: local

networks:
  transaction_network:
    driver: bridge